server:
  port: 8081
  ssl:
    bundle: server-mtls-bundle
    client-auth: need

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=TESTDB;encrypt=true;trustServerCertificate=true;
    username: sa
    password: MyPassword123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  ssl:
    bundle:
      jks:
        server-mtls-bundle:
          key:
            alias: server
          keystore:
            location: classpath:server-keystore.p12
            password: changeit
            type: PKCS12
          truststore:
            location: classpath:server-truststore.p12
            password: changeit
            type: PKCS12